/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udecaldas.edu.co.ui;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import udecaldas.edu.co.projecto.amenaza;
import udecaldas.edu.co.projecto.login;

/**
 *
 * @author yeiso
 */
public class uiModuloInfor extends javax.swing.JFrame {
    private ArrayList<amenaza> listaAmenazas;
    private HashMap<String, Integer> ataquesPorAmenaza;

    /**
     * Creates new form uiModuloInfor
     */
    public uiModuloInfor() {
        initComponents();
        listaAmenazas = new ArrayList<>();
        ataquesPorAmenaza = new HashMap<>();
        
        listaAmenazas.add(new amenaza("01AME", "Ransomware", "WannaCry, Petya, Ryuk, cifrado, rescate, malware.", 0));
        listaAmenazas.add(new amenaza("02AME", "Phishing", "Spear phishing, vishing, correo electrónico, engaño, información confidencial.", 0));
        listaAmenazas.add(new amenaza("03AME", "Ataque de Denegación de Servicio (DDoS)", "Ataque a Dyn, Mirai botnet, tráfico falso, inaccesibilidad, servicio en línea.", 0));
        listaAmenazas.add(new amenaza("04AME", "Violación de Datos", "Equifax, Yahoo, LinkedIn, acceso no autorizado, información personal, credenciales.", 0));
        listaAmenazas.add(new amenaza("05AME", "Inyección de SQL", "Ataque de inyección de SQL, código SQL malicioso, aplicación web, acceso no autorizado.", 0));
        listaAmenazas.add(new amenaza("06AME", "Malware", "virus, gusanos, troyanos, software malisioso, daño, explotacion", 0));
        listaAmenazas.add(new amenaza("07AME", "Zero-Day Exploits", "Stuxnet, vulnerabilidades, seguridad, explotación, parche.", 0));
        listaAmenazas.add(new amenaza("08AME", "Ataques a Infraestructuras Críticas", "Energía, agua, transporte, infraestructuras esenciales, compromiso", 0));
        listaAmenazas.add(new amenaza("09AME", "Ataques a Redes Sociales", "Breaches en Facebook, Twitter, acceso no autorizado, difusión de información falsa.", 0));
        listaAmenazas.add(new amenaza("10AME", "Fugas de Información Confidencial", "WikiLeaks, divulgación no autorizada, información confidencial, clasificada.", 0));
        listaAmenazas.add(new amenaza("11AME", "Hacking de Dispositivos IoT", "Ataques a cámaras de seguridad, dispositivos domésticos inteligentes, acceso no autorizado.", 0));
        listaAmenazas.add(new amenaza("12AME", "Espionaje Cibernético", "APT, Amenazas Persistentes Avanzadas, gobiernos, organizaciones, información sensible.", 0));
        
        
        for (amenaza Amenaza : listaAmenazas) {
            CmbTipoAtaque.addItem(Amenaza.getNombreAmenaza());
            ataquesPorAmenaza.put(Amenaza.getNombreAmenaza(), Amenaza.getNumeroAtaques());
        }
        
        // Agregar un ActionListener al ComboBox
        CmbTipoAtaque.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CmbTipoAtaqueActionPerformed(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        Reportar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Ataques = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CmbTipoAtaque = new javax.swing.JComboBox<>();
        txtnumeroAtaques = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        Reportar.setText("Reportar Incidente");
        Reportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarActionPerformed(evt);
            }
        });

        jLabel10.setText("Descripcion de Ataque");

        Ataques.setText("Numero Ataques");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CerrarSesion.setText("Cerrar sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de ataque");

        CmbTipoAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoAtaqueActionPerformed(evt);
            }
        });

        txtnumeroAtaques.setEditable(false);
        txtnumeroAtaques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroAtaquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CmbTipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 196, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Ataques, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumeroAtaques, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(Reportar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CerrarSesion)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CerrarSesion)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CmbTipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ataques, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumeroAtaques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addComponent(Reportar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarActionPerformed
        // TODO add your handling code here:
         // Obtener el índice seleccionado del ComboBox
    int selectedIndex = CmbTipoAtaque.getSelectedIndex();
    
    // Verificar si se seleccionó un índice válido
    if (selectedIndex >= 0) {
        // Obtener la amenaza seleccionada de la lista de amenazas usando el índice
        amenaza amenazaSeleccionada = listaAmenazas.get(selectedIndex);
        
        // Incrementar el número de ataques de la amenaza seleccionada
        amenazaSeleccionada.incrementarNumeroAtaques();
        
        // Actualizar el campo txtnumeroAtaques con el nuevo valor
        txtnumeroAtaques.setText(Integer.toString(amenazaSeleccionada.getNumeroAtaques()));
    }
    
    JOptionPane.showMessageDialog(this, "Amenza reportada"); 
        
    }//GEN-LAST:event_ReportarActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
    login loginInstance = new login(); // Crea una instancia de la clase login (si es necesario inicializarla)
    logins loginFrame = new logins(loginInstance); // Crea una instancia de logins pasando la instancia de login
    loginFrame.setVisible(true); // Hacer visible el formulario de logins
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void CmbTipoAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoAtaqueActionPerformed
        // TODO add your handling code here:
        // Obtener el índice seleccionado del ComboBox
    int selectedIndex = CmbTipoAtaque.getSelectedIndex();
    
    // Verificar si se seleccionó un índice válido
    if (selectedIndex >= 0) {
        // Obtener la amenaza seleccionada de la lista de amenazas
        amenaza amenazaSeleccionada = listaAmenazas.get(selectedIndex);
        
        // Obtener la descripción de la amenaza seleccionada
        String descripcionAmenaza = amenazaSeleccionada.getDescripcionAmenaza();
        
        // Obtener el número de ataques de la amenaza seleccionada
        int numeroAtaques = amenazaSeleccionada.getNumeroAtaques();
        
        // Establecer la descripción en el campo de texto
        jTextArea1.setText(descripcionAmenaza);
        
        // Establecer el número de ataques en el campo de texto correspondiente
        txtnumeroAtaques.setText(Integer.toString(numeroAtaques));
    }
    }//GEN-LAST:event_CmbTipoAtaqueActionPerformed

    private void txtnumeroAtaquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroAtaquesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnumeroAtaquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiModuloInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiModuloInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiModuloInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiModuloInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uiModuloInfor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ataques;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JComboBox<String> CmbTipoAtaque;
    private javax.swing.JButton Reportar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtnumeroAtaques;
    // End of variables declaration//GEN-END:variables
}
